### ISSUE TITLE
Error while running.

### ISSUE THREAD

**Issue by chirag04** [gabrielelana/node-examples#2]
I was trying to run the tic tac toe game but got this error.

throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Object function createServer() {
  if ('object' == typeof arguments[0]) {
    return new HTTPSServer(arguments[0], Array.prototype.slice.call(arguments, 1));
  } else {
    return new HTTPServer(Array.prototype.slice.call(arguments));
  }
} has no method 'staticProvider'
    at Object.<anonymous> (/media/PENDRIVE/05#tictactoe/server.js:143:15)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at Array.<anonymous> (module.js:421:10)
    at EventEmitter._tickCallback (node.js:126:26)

I'm missing something? I have installed all the required modules.

**Comment by daynight** [comment]
Chirag: You will have to edit the server.js file
Online 143 or 144 you will find a connect.staticProvider({blah-blah..  
Change it to this: connect.static({blah-blah..
That should get it working
